### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [bartavelle/hruby#28]
```
hruby                          > Building library for hruby-0.3.8.1..
hruby                          > [1 of 4] Compiling Foreign.Ruby.Bindings
hruby                          > [2 of 4] Compiling Foreign.Ruby.Helpers
hruby                          > 
hruby                          > /tmp/stack-b1b9478f83173021/hruby-0.3.8.1/Foreign/Ruby/Helpers.hs:123:39: error:
hruby                          >     • Couldn't match type: HM.HashMap k v
hruby                          >                      with: Data.Aeson.KeyMap.KeyMap Value
hruby                          >       Expected: [(k, v)] -> Object
hruby                          >         Actual: [(k, v)] -> HM.HashMap k v
hruby                          >     • In the second argument of ‘(.)’, namely ‘HM.fromList’
hruby                          >       In the expression: Object . HM.fromList
hruby                          >       In an equation for ‘toHash’: toHash = Object . HM.fromList
hruby                          >     • Relevant bindings include
hruby                          >         toHash :: [(k, v)] -> Value
hruby                          >           (bound at Foreign/Ruby/Helpers.hs:123:21)
hruby                          >     |
hruby                          > 123 |                     toHash = Object . HM.fromList
hruby                          >     |                                       ^^^^^^^^^^^
hruby                          > 
hruby                          > /tmp/stack-b1b9478f83173021/hruby-0.3.8.1/Foreign/Ruby/Helpers.hs:144:26: error:
hruby                          >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
hruby                          >                      with: HM.HashMap a0 a1
hruby                          >       Expected: HM.HashMap a0 a1
hruby                          >         Actual: Object
hruby                          >     • In the first argument of ‘HM.toList’, namely ‘m’
hruby                          >       In the first argument of ‘forM_’, namely ‘(HM.toList m)’
hruby                          >       In the first argument of ‘($)’, namely ‘forM_ (HM.toList m)’
hruby                          >     |
hruby                          > 144 |         forM_ (HM.toList m) $ \(k, v) -> do
hruby                          >     |                          ^
```

**Comment by bartavelle** [comment]
Just released 0.4.0.0, should be fixed :)
