### ISSUE TITLE
Failure with Ruby 3.1.4

### ISSUE THREAD

**Issue by PierreR** [bartavelle/hruby#29]
I have this failure using ruby 3.1.4
Not sure if it is the way I am building hruby or the fact that I am now using ruby 3.x.y.
```
undefined method `current' for Ractor:Class
/nix/store/v001jk4sximy2fn9c704dj64a2vwfxsm-ruby-3.1.4/lib/ruby/3.1.0/psych.rb:727:in `config'
/nix/store/v001jk4sximy2fn9c704dj64a2vwfxsm-ruby-3.1.4/lib/ruby/3.1.0/forwardable.rb:232:in `load_tags='
/nix/store/v001jk4sximy2fn9c704dj64a2vwfxsm-ruby-3.1.4/lib/ruby/3.1.0/psych.rb:737:in `<module:Psych>'
/nix/store/v001jk4sximy2fn9c704dj64a2vwfxsm-ruby-3.1.4/lib/ruby/3.1.0/psych.rb:234:in `<top (required)>'
/nix/store/v001jk4sximy2fn9c704dj64a2vwfxsm-ruby-3.1.4/lib/ruby/3.1.0/yaml.rb:4:in `require'
/nix/store/v001jk4sximy2fn9c704dj64a2vwfxsm-ruby-3.1.4/lib/ruby/3.1.0/yaml.rb:4:in `<top (required)>'
```
Any idea ?

**Comment by bartavelle** [comment]
Ruby 3 is most certainly unsupported as of now. I'll try to take a look. which distribution are you using?

**Comment by PierreR** [comment]
@bartavelle I am using an isolated environment build with nix (https://nixos.org/). It doesn't matter much but I am on WSL (Ubuntu). 
I have switched to Ruby 3 because Ruby 2 is EOL.

**Comment by bartavelle** [comment]
It is completely busted with ruby 3.0 :sob:

**Comment by bartavelle** [comment]
OK I give up for now, there is some memory corruption happening, and I don't think I can spend hours chasing after that. Perhaps I will have an illumination in the following days though.

**Comment by PierreR** [comment]
@bartavelle On my side, I can still make it work with ruby 2.7.6 (ghc 8.10) but as soon as I switch to ruby2.7.8 (ghc 9.2.8) I have this error:

>  allocaBytesAligned: invalid argument (alignment (=152) must be a power of two!) 

As surprising as it sounds, I guess this is due to the change from ruby 2.7.6 to 2.7.8 ?
 
Would be handy if I am able to switch to ruby 2.7.8 (ghc 9.2.8).

Thanks

**Comment by PierreR** [comment]
The error arises at the content of ERB template. For instance:  `content => template('sudo/sudoers.erb'),`

**Comment by bartavelle** [comment]
I just pushed a fix
